package com.bzw.api.module.basic.model;

public class Employee {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.name
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.phone
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.sex
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.is_tenant_supper
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Byte isTenantSupper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.is_branch_super
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Byte isBranchSuper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.branch_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.tenant_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.user_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.status_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.wechat_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private String wechatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.role_type
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private Integer roleType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_employee.branch_name
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    private String branchName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.id
     *
     * @return the value of biz_employee.id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.id
     *
     * @param id the value for biz_employee.id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.name
     *
     * @return the value of biz_employee.name
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.name
     *
     * @param name the value for biz_employee.name
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.phone
     *
     * @return the value of biz_employee.phone
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.phone
     *
     * @param phone the value for biz_employee.phone
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.sex
     *
     * @return the value of biz_employee.sex
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.sex
     *
     * @param sex the value for biz_employee.sex
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.is_tenant_supper
     *
     * @return the value of biz_employee.is_tenant_supper
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Byte getIsTenantSupper() {
        return isTenantSupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.is_tenant_supper
     *
     * @param isTenantSupper the value for biz_employee.is_tenant_supper
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setIsTenantSupper(Byte isTenantSupper) {
        this.isTenantSupper = isTenantSupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.is_branch_super
     *
     * @return the value of biz_employee.is_branch_super
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Byte getIsBranchSuper() {
        return isBranchSuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.is_branch_super
     *
     * @param isBranchSuper the value for biz_employee.is_branch_super
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setIsBranchSuper(Byte isBranchSuper) {
        this.isBranchSuper = isBranchSuper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.branch_id
     *
     * @return the value of biz_employee.branch_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.branch_id
     *
     * @param branchId the value for biz_employee.branch_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.tenant_id
     *
     * @return the value of biz_employee.tenant_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.tenant_id
     *
     * @param tenantId the value for biz_employee.tenant_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.user_id
     *
     * @return the value of biz_employee.user_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.user_id
     *
     * @param userId the value for biz_employee.user_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.status_id
     *
     * @return the value of biz_employee.status_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.status_id
     *
     * @param statusId the value for biz_employee.status_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.wechat_id
     *
     * @return the value of biz_employee.wechat_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.wechat_id
     *
     * @param wechatId the value for biz_employee.wechat_id
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.role_type
     *
     * @return the value of biz_employee.role_type
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public Integer getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.role_type
     *
     * @param roleType the value for biz_employee.role_type
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setRoleType(Integer roleType) {
        this.roleType = roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_employee.branch_name
     *
     * @return the value of biz_employee.branch_name
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_employee.branch_name
     *
     * @param branchName the value for biz_employee.branch_name
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
}