package com.bzw.api.module.basic.model;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_message.id
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_message.sender
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_message.receiver
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    private String receiver;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_message.json
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    private String json;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_message.content
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_message.created_date
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_message.is_finish
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    private Byte isFinish;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_message.id
     *
     * @return the value of pl_message.id
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_message.id
     *
     * @param id the value for pl_message.id
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_message.sender
     *
     * @return the value of pl_message.sender
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_message.sender
     *
     * @param sender the value for pl_message.sender
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public void setSender(String sender) {
        this.sender = sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_message.receiver
     *
     * @return the value of pl_message.receiver
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_message.receiver
     *
     * @param receiver the value for pl_message.receiver
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_message.json
     *
     * @return the value of pl_message.json
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public String getJson() {
        return json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_message.json
     *
     * @param json the value for pl_message.json
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public void setJson(String json) {
        this.json = json;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_message.content
     *
     * @return the value of pl_message.content
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_message.content
     *
     * @param content the value for pl_message.content
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_message.created_date
     *
     * @return the value of pl_message.created_date
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_message.created_date
     *
     * @param createdDate the value for pl_message.created_date
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_message.is_finish
     *
     * @return the value of pl_message.is_finish
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public Byte getIsFinish() {
        return isFinish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_message.is_finish
     *
     * @param isFinish the value for pl_message.is_finish
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    public void setIsFinish(Byte isFinish) {
        this.isFinish = isFinish;
    }
}