package com.bzw.api.module.basic.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.created_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.biz_status_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private Integer bizStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.price
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.pay_price
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private BigDecimal payPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.branch_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.tenant_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.pay_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_order.modified_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    private Date modifiedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.id
     *
     * @return the value of biz_order.id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.id
     *
     * @param id the value for biz_order.id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.created_time
     *
     * @return the value of biz_order.created_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.created_time
     *
     * @param createdTime the value for biz_order.created_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.biz_status_id
     *
     * @return the value of biz_order.biz_status_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public Integer getBizStatusId() {
        return bizStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.biz_status_id
     *
     * @param bizStatusId the value for biz_order.biz_status_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setBizStatusId(Integer bizStatusId) {
        this.bizStatusId = bizStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.price
     *
     * @return the value of biz_order.price
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.price
     *
     * @param price the value for biz_order.price
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.pay_price
     *
     * @return the value of biz_order.pay_price
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public BigDecimal getPayPrice() {
        return payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.pay_price
     *
     * @param payPrice the value for biz_order.pay_price
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setPayPrice(BigDecimal payPrice) {
        this.payPrice = payPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.branch_id
     *
     * @return the value of biz_order.branch_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.branch_id
     *
     * @param branchId the value for biz_order.branch_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.tenant_id
     *
     * @return the value of biz_order.tenant_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.tenant_id
     *
     * @param tenantId the value for biz_order.tenant_id
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.pay_time
     *
     * @return the value of biz_order.pay_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.pay_time
     *
     * @param payTime the value for biz_order.pay_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_order.modified_time
     *
     * @return the value of biz_order.modified_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_order.modified_time
     *
     * @param modifiedTime the value for biz_order.modified_time
     *
     * @mbggenerated Mon Jan 08 16:13:48 CST 2018
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }
}