package com.bzw.api.module.basic.model;

import java.util.Date;

public class RecordChange {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_record_change.id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_record_change.type
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_record_change.document_id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    private Long documentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_record_change.content
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_record_change.chnage_date
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    private Date chnageDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_record_change.tenant_id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    private Long tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_record_change.id
     *
     * @return the value of biz_record_change.id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_record_change.id
     *
     * @param id the value for biz_record_change.id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_record_change.type
     *
     * @return the value of biz_record_change.type
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_record_change.type
     *
     * @param type the value for biz_record_change.type
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_record_change.document_id
     *
     * @return the value of biz_record_change.document_id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public Long getDocumentId() {
        return documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_record_change.document_id
     *
     * @param documentId the value for biz_record_change.document_id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public void setDocumentId(Long documentId) {
        this.documentId = documentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_record_change.content
     *
     * @return the value of biz_record_change.content
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_record_change.content
     *
     * @param content the value for biz_record_change.content
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_record_change.chnage_date
     *
     * @return the value of biz_record_change.chnage_date
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public Date getChnageDate() {
        return chnageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_record_change.chnage_date
     *
     * @param chnageDate the value for biz_record_change.chnage_date
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public void setChnageDate(Date chnageDate) {
        this.chnageDate = chnageDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_record_change.tenant_id
     *
     * @return the value of biz_record_change.tenant_id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_record_change.tenant_id
     *
     * @param tenantId the value for biz_record_change.tenant_id
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }
}