package com.bzw.api.module.basic.model;

public class RoomKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_room.id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_room.branch_id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_room.tenant_id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    private Long tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_room.id
     *
     * @return the value of biz_room.id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_room.id
     *
     * @param id the value for biz_room.id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_room.branch_id
     *
     * @return the value of biz_room.branch_id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_room.branch_id
     *
     * @param branchId the value for biz_room.branch_id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_room.tenant_id
     *
     * @return the value of biz_room.tenant_id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_room.tenant_id
     *
     * @param tenantId the value for biz_room.tenant_id
     *
     * @mbggenerated Tue Jan 02 20:55:25 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }
}