package com.bzw.api.module.basic.model;

public class Tag {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tag.id
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tag.name
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tag.type
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tag.tenant_id
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    private Long tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tag.id
     *
     * @return the value of biz_tag.id
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tag.id
     *
     * @param id the value for biz_tag.id
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tag.name
     *
     * @return the value of biz_tag.name
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tag.name
     *
     * @param name the value for biz_tag.name
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tag.type
     *
     * @return the value of biz_tag.type
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tag.type
     *
     * @param type the value for biz_tag.type
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tag.tenant_id
     *
     * @return the value of biz_tag.tenant_id
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tag.tenant_id
     *
     * @param tenantId the value for biz_tag.tenant_id
     *
     * @mbggenerated Mon Jan 29 17:42:57 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }
}