package com.bzw.api.module.basic.model;

public class TechnicianAssess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_assess.id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_assess.grade
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_assess.technician_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    private Long technicianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_assess.branch_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_assess.tenant_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_assess.order_detail_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    private Long orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_assess.wechat_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    private String wechatId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_assess.id
     *
     * @return the value of biz_technician_assess.id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_assess.id
     *
     * @param id the value for biz_technician_assess.id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_assess.grade
     *
     * @return the value of biz_technician_assess.grade
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_assess.grade
     *
     * @param grade the value for biz_technician_assess.grade
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_assess.technician_id
     *
     * @return the value of biz_technician_assess.technician_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public Long getTechnicianId() {
        return technicianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_assess.technician_id
     *
     * @param technicianId the value for biz_technician_assess.technician_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public void setTechnicianId(Long technicianId) {
        this.technicianId = technicianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_assess.branch_id
     *
     * @return the value of biz_technician_assess.branch_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_assess.branch_id
     *
     * @param branchId the value for biz_technician_assess.branch_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_assess.tenant_id
     *
     * @return the value of biz_technician_assess.tenant_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_assess.tenant_id
     *
     * @param tenantId the value for biz_technician_assess.tenant_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_assess.order_detail_id
     *
     * @return the value of biz_technician_assess.order_detail_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_assess.order_detail_id
     *
     * @param orderDetailId the value for biz_technician_assess.order_detail_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_assess.wechat_id
     *
     * @return the value of biz_technician_assess.wechat_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_assess.wechat_id
     *
     * @param wechatId the value for biz_technician_assess.wechat_id
     *
     * @mbggenerated Sun Jan 28 16:41:29 CST 2018
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }
}