package com.bzw.api.module.basic.model;

public class TechnicianAssess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_ assess.id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_ assess.grade
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    private Integer grade;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_ assess.technician_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    private Long technicianId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_ assess.branch_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_ assess.tenant_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_ assess.order_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    private Long orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician_ assess.wechat_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    private String wechatId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_ assess.id
     *
     * @return the value of biz_technician_ assess.id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_ assess.id
     *
     * @param id the value for biz_technician_ assess.id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_ assess.grade
     *
     * @return the value of biz_technician_ assess.grade
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_ assess.grade
     *
     * @param grade the value for biz_technician_ assess.grade
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_ assess.technician_id
     *
     * @return the value of biz_technician_ assess.technician_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public Long getTechnicianId() {
        return technicianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_ assess.technician_id
     *
     * @param technicianId the value for biz_technician_ assess.technician_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public void setTechnicianId(Long technicianId) {
        this.technicianId = technicianId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_ assess.branch_id
     *
     * @return the value of biz_technician_ assess.branch_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_ assess.branch_id
     *
     * @param branchId the value for biz_technician_ assess.branch_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_ assess.tenant_id
     *
     * @return the value of biz_technician_ assess.tenant_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_ assess.tenant_id
     *
     * @param tenantId the value for biz_technician_ assess.tenant_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_ assess.order_id
     *
     * @return the value of biz_technician_ assess.order_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_ assess.order_id
     *
     * @param orderId the value for biz_technician_ assess.order_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician_ assess.wechat_id
     *
     * @return the value of biz_technician_ assess.wechat_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician_ assess.wechat_id
     *
     * @param wechatId the value for biz_technician_ assess.wechat_id
     *
     * @mbggenerated Fri Jan 05 17:25:14 CST 2018
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }
}