package com.bzw.api.module.basic.model;

import java.util.Date;

public class Technician {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.age
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.description
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.phone
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.branch_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.tenant_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.status_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.created_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long createdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.created_date
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.modified_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long modifiedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.modified_date
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Date modifiedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.biz_status_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Integer bizStatusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.employee_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long employeeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.branch_name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.job_number
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private String jobNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.praise
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Integer praise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.order_count
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Integer orderCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.start_time
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Date startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.over_time
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Date overTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.order_detail_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long orderDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.room_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private Long roomId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.room_name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private String roomName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_technician.wechat_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    private String wechatId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.id
     *
     * @return the value of biz_technician.id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.id
     *
     * @param id the value for biz_technician.id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.name
     *
     * @return the value of biz_technician.name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.name
     *
     * @param name the value for biz_technician.name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.age
     *
     * @return the value of biz_technician.age
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.age
     *
     * @param age the value for biz_technician.age
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.description
     *
     * @return the value of biz_technician.description
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.description
     *
     * @param description the value for biz_technician.description
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.phone
     *
     * @return the value of biz_technician.phone
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.phone
     *
     * @param phone the value for biz_technician.phone
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.branch_id
     *
     * @return the value of biz_technician.branch_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.branch_id
     *
     * @param branchId the value for biz_technician.branch_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.tenant_id
     *
     * @return the value of biz_technician.tenant_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.tenant_id
     *
     * @param tenantId the value for biz_technician.tenant_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.status_id
     *
     * @return the value of biz_technician.status_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.status_id
     *
     * @param statusId the value for biz_technician.status_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.created_id
     *
     * @return the value of biz_technician.created_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getCreatedId() {
        return createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.created_id
     *
     * @param createdId the value for biz_technician.created_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setCreatedId(Long createdId) {
        this.createdId = createdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.created_date
     *
     * @return the value of biz_technician.created_date
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.created_date
     *
     * @param createdDate the value for biz_technician.created_date
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.modified_id
     *
     * @return the value of biz_technician.modified_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getModifiedId() {
        return modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.modified_id
     *
     * @param modifiedId the value for biz_technician.modified_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setModifiedId(Long modifiedId) {
        this.modifiedId = modifiedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.modified_date
     *
     * @return the value of biz_technician.modified_date
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Date getModifiedDate() {
        return modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.modified_date
     *
     * @param modifiedDate the value for biz_technician.modified_date
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setModifiedDate(Date modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.biz_status_id
     *
     * @return the value of biz_technician.biz_status_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Integer getBizStatusId() {
        return bizStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.biz_status_id
     *
     * @param bizStatusId the value for biz_technician.biz_status_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setBizStatusId(Integer bizStatusId) {
        this.bizStatusId = bizStatusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.employee_id
     *
     * @return the value of biz_technician.employee_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getEmployeeId() {
        return employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.employee_id
     *
     * @param employeeId the value for biz_technician.employee_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setEmployeeId(Long employeeId) {
        this.employeeId = employeeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.branch_name
     *
     * @return the value of biz_technician.branch_name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.branch_name
     *
     * @param branchName the value for biz_technician.branch_name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.job_number
     *
     * @return the value of biz_technician.job_number
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public String getJobNumber() {
        return jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.job_number
     *
     * @param jobNumber the value for biz_technician.job_number
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setJobNumber(String jobNumber) {
        this.jobNumber = jobNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.praise
     *
     * @return the value of biz_technician.praise
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Integer getPraise() {
        return praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.praise
     *
     * @param praise the value for biz_technician.praise
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setPraise(Integer praise) {
        this.praise = praise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.order_count
     *
     * @return the value of biz_technician.order_count
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Integer getOrderCount() {
        return orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.order_count
     *
     * @param orderCount the value for biz_technician.order_count
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setOrderCount(Integer orderCount) {
        this.orderCount = orderCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.start_time
     *
     * @return the value of biz_technician.start_time
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.start_time
     *
     * @param startTime the value for biz_technician.start_time
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.over_time
     *
     * @return the value of biz_technician.over_time
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Date getOverTime() {
        return overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.over_time
     *
     * @param overTime the value for biz_technician.over_time
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setOverTime(Date overTime) {
        this.overTime = overTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.order_detail_id
     *
     * @return the value of biz_technician.order_detail_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getOrderDetailId() {
        return orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.order_detail_id
     *
     * @param orderDetailId the value for biz_technician.order_detail_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setOrderDetailId(Long orderDetailId) {
        this.orderDetailId = orderDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.room_id
     *
     * @return the value of biz_technician.room_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public Long getRoomId() {
        return roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.room_id
     *
     * @param roomId the value for biz_technician.room_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setRoomId(Long roomId) {
        this.roomId = roomId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.room_name
     *
     * @return the value of biz_technician.room_name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public String getRoomName() {
        return roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.room_name
     *
     * @param roomName the value for biz_technician.room_name
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setRoomName(String roomName) {
        this.roomName = roomName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_technician.wechat_id
     *
     * @return the value of biz_technician.wechat_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public String getWechatId() {
        return wechatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_technician.wechat_id
     *
     * @param wechatId the value for biz_technician.wechat_id
     *
     * @mbggenerated Wed Jan 24 17:03:01 CST 2018
     */
    public void setWechatId(String wechatId) {
        this.wechatId = wechatId;
    }
}