package com.bzw.api.module.main.dto;

import com.bzw.api.module.base.model.Technician;
import com.bzw.api.module.base.model.TechnicianExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TechnicianMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int countByExample(TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int deleteByExample(TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int insert(Technician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int insertSelective(Technician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    List<Technician> selectByExample(TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    Technician selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int updateByExampleSelective(@Param("record") Technician record, @Param("example") TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int updateByExample(@Param("record") Technician record, @Param("example") TechnicianExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int updateByPrimaryKeySelective(Technician record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician
     *
     * @mbggenerated Sat Jan 20 17:51:25 CST 2018
     */
    int updateByPrimaryKey(Technician record);
}