package com.bzw.api.module.base.dao;

import com.bzw.api.module.base.model.Picture;
import com.bzw.api.module.base.model.PictureExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int countByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int deleteByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int insertSelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    List<Picture> selectByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    Picture selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int updateByExampleSelective(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int updateByExample(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int updateByPrimaryKeySelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_picture
     *
     * @mbggenerated Fri Feb 02 11:13:22 CST 2018
     */
    int updateByPrimaryKey(Picture record);
}