package com.bzw.api.module.base.dao;

import com.bzw.api.module.base.model.RecordChange;
import com.bzw.api.module.base.model.RecordChangeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RecordChangeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int countByExample(RecordChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int deleteByExample(RecordChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int insert(RecordChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int insertSelective(RecordChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    List<RecordChange> selectByExample(RecordChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    RecordChange selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") RecordChange record, @Param("example") RecordChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int updateByExample(@Param("record") RecordChange record, @Param("example") RecordChangeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int updateByPrimaryKeySelective(RecordChange record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_record_change
     *
     * @mbggenerated Fri Jan 05 14:18:08 CST 2018
     */
    int updateByPrimaryKey(RecordChange record);
}