package com.bzw.api.module.base.dao;

import com.bzw.api.module.base.model.TechnicianProject;
import com.bzw.api.module.base.model.TechnicianProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TechnicianProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int countByExample(TechnicianProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int deleteByExample(TechnicianProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int insert(TechnicianProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int insertSelective(TechnicianProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    List<TechnicianProject> selectByExample(TechnicianProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    TechnicianProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int updateByExampleSelective(@Param("record") TechnicianProject record, @Param("example") TechnicianProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int updateByExample(@Param("record") TechnicianProject record, @Param("example") TechnicianProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int updateByPrimaryKeySelective(TechnicianProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_technician_project
     *
     * @mbggenerated Tue Jan 23 11:26:42 CST 2018
     */
    int updateByPrimaryKey(TechnicianProject record);
}