package com.bzw.api.module.base.model;

import java.math.BigDecimal;

public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.name
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.branch_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private Long branchId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.tenant_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private Long tenantId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.price
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.status_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.type
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.branch_name
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private String branchName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.duration
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_project.description
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.id
     *
     * @return the value of biz_project.id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.id
     *
     * @param id the value for biz_project.id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.name
     *
     * @return the value of biz_project.name
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.name
     *
     * @param name the value for biz_project.name
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.branch_id
     *
     * @return the value of biz_project.branch_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public Long getBranchId() {
        return branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.branch_id
     *
     * @param branchId the value for biz_project.branch_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setBranchId(Long branchId) {
        this.branchId = branchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.tenant_id
     *
     * @return the value of biz_project.tenant_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public Long getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.tenant_id
     *
     * @param tenantId the value for biz_project.tenant_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setTenantId(Long tenantId) {
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.price
     *
     * @return the value of biz_project.price
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.price
     *
     * @param price the value for biz_project.price
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.status_id
     *
     * @return the value of biz_project.status_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.status_id
     *
     * @param statusId the value for biz_project.status_id
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.type
     *
     * @return the value of biz_project.type
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.type
     *
     * @param type the value for biz_project.type
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.branch_name
     *
     * @return the value of biz_project.branch_name
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.branch_name
     *
     * @param branchName the value for biz_project.branch_name
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.duration
     *
     * @return the value of biz_project.duration
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.duration
     *
     * @param duration the value for biz_project.duration
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_project.description
     *
     * @return the value of biz_project.description
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_project.description
     *
     * @param description the value for biz_project.description
     *
     * @mbggenerated Tue Jan 23 11:06:02 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}