package com.bzw.api.module.base.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_role.id
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_role.name
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pl_role.description
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_role.id
     *
     * @return the value of pl_role.id
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_role.id
     *
     * @param id the value for pl_role.id
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_role.name
     *
     * @return the value of pl_role.name
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_role.name
     *
     * @param name the value for pl_role.name
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pl_role.description
     *
     * @return the value of pl_role.description
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pl_role.description
     *
     * @param description the value for pl_role.description
     *
     * @mbggenerated Thu Feb 08 09:32:52 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }
}