package com.bzw.api.module.base.model;

import java.util.Date;

public class Tenant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tenant.id
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tenant.name
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tenant.status_id
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    private Integer statusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tenant.created_time
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tenant.modified_time
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column biz_tenant.phone
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tenant.id
     *
     * @return the value of biz_tenant.id
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tenant.id
     *
     * @param id the value for biz_tenant.id
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tenant.name
     *
     * @return the value of biz_tenant.name
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tenant.name
     *
     * @param name the value for biz_tenant.name
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tenant.status_id
     *
     * @return the value of biz_tenant.status_id
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public Integer getStatusId() {
        return statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tenant.status_id
     *
     * @param statusId the value for biz_tenant.status_id
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tenant.created_time
     *
     * @return the value of biz_tenant.created_time
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tenant.created_time
     *
     * @param createdTime the value for biz_tenant.created_time
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tenant.modified_time
     *
     * @return the value of biz_tenant.modified_time
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tenant.modified_time
     *
     * @param modifiedTime the value for biz_tenant.modified_time
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column biz_tenant.phone
     *
     * @return the value of biz_tenant.phone
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column biz_tenant.phone
     *
     * @param phone the value for biz_tenant.phone
     *
     * @mbggenerated Wed Jan 03 23:03:00 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}