package com.bzw.api.module.basic.dao;

import com.bzw.api.module.basic.model.Branch;
import com.bzw.api.module.basic.model.BranchExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BranchMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int countByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int deleteByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int insert(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int insertSelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    List<Branch> selectByExample(BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    Branch selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int updateByExampleSelective(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int updateByExample(@Param("record") Branch record, @Param("example") BranchExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int updateByPrimaryKeySelective(Branch record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_branch
     *
     * @mbggenerated Wed Jan 03 17:05:34 CST 2018
     */
    int updateByPrimaryKey(Branch record);
}