package com.bzw.api.module.basic.dao;

import com.bzw.api.module.basic.model.Employee;
import com.bzw.api.module.basic.model.EmployeeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int countByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int deleteByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int insertSelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    List<Employee> selectByExample(EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    Employee selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int updateByExample(@Param("record") Employee record, @Param("example") EmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int updateByPrimaryKeySelective(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_employee
     *
     * @mbggenerated Mon Jan 08 10:58:51 CST 2018
     */
    int updateByPrimaryKey(Employee record);
}