package com.bzw.api.module.basic.dao;

import com.bzw.api.module.basic.model.Message;
import com.bzw.api.module.basic.model.MessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    Message selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int updateByPrimaryKeySelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pl_message
     *
     * @mbggenerated Tue Jan 30 17:03:39 CST 2018
     */
    int updateByPrimaryKey(Message record);
}