package com.bzw.api.module.basic.dao;

import com.bzw.api.module.basic.model.RoomProject;
import com.bzw.api.module.basic.model.RoomProjectExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoomProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int countByExample(RoomProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int deleteByExample(RoomProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int deleteByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int insert(RoomProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int insertSelective(RoomProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    List<RoomProject> selectByExample(RoomProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    RoomProject selectByPrimaryKey(Long roomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int updateByExampleSelective(@Param("record") RoomProject record, @Param("example") RoomProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int updateByExample(@Param("record") RoomProject record, @Param("example") RoomProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int updateByPrimaryKeySelective(RoomProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table biz_room_project
     *
     * @mbggenerated Wed Jan 03 22:57:53 CST 2018
     */
    int updateByPrimaryKey(RoomProject record);
}